최근 본 제품 영역 UI를 구현했습니다. (타이틀 및 컬렉션 뷰)
SnoopClass/Noel-Student-IKEA pull request #6
Opened 2022-10-10 05:16 UTC by GODNOEL

## 👀 관련 이슈

#3 

## 👀 배경

###  두번째 구역인 타이틀과 최근 본 상품 목록이 있는 RecentProductSectionView을 구현했습니다.
<img src="https://user-images.githubusercontent.com/103012104/194801221-487c79cb-d93e-4284-a211-762783a7b8f6.jpeg"  width="250" />

## 👀 작업 내용
### 1. 타이틀 영역
- title과 삭제버튼 모두 UILable로 구현했습니다.
- 삭제 버튼 이벤트는 UILable에 gesture를 주는 형태로 구현할 예정입니다!

### 2. 최근 본 제품 `CollectView`
- 최근 본 제품 CollectView는 일단 UI를 확인하기 위해 제가 정한 임의의 숫자와 이미지로 제작했습니다.
- 최근 본 제품 데이터 파일을 만들어 CollectView에 적용할 예정입니다!

<img src="https://user-images.githubusercontent.com/103012104/194801301-ebcfb915-20c5-4aa6-bd6d-f86e7fe0f027.gif"  width="250" />

### 3. 폴더구조
- 저번에 제가 만든 폴더 구조는 효율적이라고 생각되지않아 이 PR이 끝나면 전반적인 폴더구조를 한번 정리할 예정입니다.
 > SupportingView에 UIView를 넣다보니 그 UIView를 도와주는? 구성하는 Cell 파일을 어디 넣을지 애매해져서..ㅜㅜ
<img width="250" alt="image" src="https://user-images.githubusercontent.com/103012104/194802004-9187938e-659a-408b-bdc5-2ecbc764c3e3.png">

## 👀 PR Point
- 변수명이 적절한지
- AutoLayout의 사용이 적절한지
- 메소드 사용이 적절한지
 - 그외 개선이 필요한 구현 방식이 있는지
위 사항을 위주로 말씀해주시면 감사하겠습니다!

## 👀 참고 사항
- 모두삭제 이벤트 및 제품페이지 연결은 구현 예정입니다!
### stackView에 Margin을 넣기
각 영역이 상단과 왼쪽은 동일 값이 반복된다고 생각해  
stackView에  Margin을 넣으면 더 편하게 구현할 수 있지 않을까 싶어서 구현했다가
CollectView가 전체 너비를 사용하고 있어 빠지게 되었는데 알아두면 좋지않을까 싶어 레퍼런스 공유해요! 

https://velog.io/@dvhuni/UIStackView-Margin-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0

2022-10-10 09:29 UTC, siro96-01 commented
코드를 분석해보고있어용 ㅠ 조금 시간이 걸릴거 같네요

2022-10-11 10:03 UTC, compuTasha requested changes
고생하셨습니다!!
노엘 코드 보고 저도 코드 베이스로 UI 짜는 방법 공부하고 갑니다... 총총..🌝

커밋할 때 이슈 넘버 잊지 말아주세요.. Remember me...

2022-10-11 10:03 UTC, compuTasha commented on IKEA/IKEA/SearchViewController.swift
>      private lazy var stackView: UIStackView = {
p5;

stackView를 `lazy var`로 구현한 부분에 대해서
현재 이케아 화면은 한정된 이미지만을 (최대 5개) 뷰에 보여주고 있어서 
저는 `lazy var` 로 구현하지 않아도 된다고 생각했습니다..!
`lazy var` 기준이 항상 애매하네요.. 혹시 어떻게 생각하시나요??

제가 인상깊게 본 스택오버플로우 답변은 아래와 같습니다! 정리하자면..
" `lazy`를 코드에 얼마나 쓰던 메모리에 해를 끼치지는 않지만, 가독성을 위해 `lazy`를 썼을 때 효과 있는 부분에만 쓰자! 근데 거의 대부분의 경우에는 `lazy`가 좋긴하더라~" 
" `lazy`를 남용하면 메모리 복잡도는 감소하지만 시간 복잡도는 증가할거야~"
인데,, 그래서 지금은 쓰라는건지 말라는건지 모르겠어요... 같이 고민해봐요!!

참고한 스택오버플로우 링크:
https://stackoverflow.com/questions/51398806/is-lazy-keywords-harmful-for-memory-or-performance
`lazy`를 잘 설명한 글:
https://abhimuralidharan.medium.com/lazy-var-in-ios-swift-96c75cb8a13a
https://mikebuss.com/2014/06/22/lazy-initialization-swift/

2022-10-11 10:03 UTC, compuTasha commented on IKEA/IKEA/SupportingView/SearchBarSectionView.swift
> +            searchBarbackground.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant:  -30),
p2;

여기 불필요한 공백이 들어간 것 같아요!!👀
불필요한 공백이라면.. 스슥 삭제 어떨까요..?!

2022-10-11 10:03 UTC, compuTasha commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +        $0.text = "최근 본 제픔"
p2;

제,,, 픔,,, 내 픔으로,,,

장난입니다 죄송합니다.. 여기 오타가 있는 것 같아요!

2022-10-11 10:03 UTC, compuTasha commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    private let titleLable: UILabel = {
p2;

Label 을 적으려고 하신 게 맞을까요?!
맞다면 수정이 필요해보여요!

2022-10-11 10:03 UTC, compuTasha commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    private let deleteLable: UILabel = {
p2;

Label 을 적으려고 하신 게 맞을까요?!
맞다면 여기도 수정이 필요해보여요! 👀

2022-10-11 10:23 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/SearchBarSectionView.swift
> +            searchBarbackground.trailingAnchor.constraint(equalTo: self.trailingAnchor, constant:  -30),
감사합니당 로라 덕분에 깔끔한 코드 ^^
수정 반영했습니다!

1b204ddaf5f46ce5cccb832eb3ad8e0b668d9eb0

2022-10-11 10:24 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +        $0.text = "최근 본 제픔"
로라 품으로 지금 가면 될까여?🙃?
수정 반영했습니다! 오타 발견 감사합니다!

1b204ddaf5f46ce5cccb832eb3ad8e0b668d9eb0

2022-10-11 10:26 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    private let titleLable: UILabel = {
헤헤 자꾸 Label에서 오타가 나네요.. (민망..)
다음부터는 좀 더 뇌에 힘주고 작업하겠습니다!
수정 반영했습니다!

1b204ddaf5f46ce5cccb832eb3ad8e0b668d9eb0

2022-10-11 10:26 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    private let deleteLable: UILabel = {
수정했습니다!!

1b204ddaf5f46ce5cccb832eb3ad8e0b668d9eb0

2022-10-11 10:28 UTC, compuTasha approved these changes
수정 사항 확인했습니다!!
빠른 수정 감사합니다🔥

2022-10-11 11:10 UTC, siro96-01 commented
깔끔하고 좋은 코드 감사합니다. 보면서 정말 공부가 많이 되네요. 
PR에 코드를 리뷰하는건 처음이라서 좀 어색한데 몇가지 궁금한점이나 수정 제한사항(?)을 올릴게요.

2022-10-11 11:29 UTC, siro96-01 reviewed
좋은코드 너무너무 멋있어요 노엘!

2022-10-11 11:29 UTC, siro96-01 commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    }
```suggestion
      let size = RecentProductCollectView.frame.width / 5
        let cellSize = CGSize(width: size, height: size)
        return cellSize
    }
```
진짜진짜 별거는 아닌데 일단 코드 리뷰할 거리를 만들기 위해서 생각한 대안입니다. 
이런식으로 한번 더 프로퍼티로 담아서 리턴하면 추후에 혹여나 크기 수정할때에 더 용이한 코드가 될 수 있지 않을까..!! 해서 
간언드리옵니다 폐하.

2022-10-11 11:29 UTC, siro96-01 commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    }
이부분은 질문입니다. collectionView(minimumLineSpacingForSectionAt:_)는 셀과 셀 사이의 위 아래 간격 사이 거리를 설정하는걸로 알고있는데 RecentProductCollectView는  한줄짜리 collectionView라서 사용하지 않아도 된다고 생각했거든요. 
혹시 사용하신 이유가 따로 있으신지 궁금합니다!

2022-10-11 13:15 UTC, GODNOEL commented on IKEA/IKEA/SearchViewController.swift
>      private lazy var stackView: UIStackView = {
## 리뷰 감사합니다! 
로라! `lazy var` 에 대해 잘 정리한 리뷰 달아주셔서 너무 감사합니다!!🥰😆
저도 `lazy var`를 사용함에 있어 뭐가 맞는건지 항상 고민하고 있는데요!

일단 제가 `lazy var`를 사용한 이유를 말씀드리자면 
현재 제가 구현한 방식은 `stackView`애 각 영역이 `UIVIew`로 들어가고 있습니다.
각 `UIView`는 이미지와 소스들이 들어가게 되어 `stackView`를 `lazy var`로 구현하게 되면 
아직 스크롤하지 않은 영역들은 메모리에 올라오지 않아
좀 더 메모리를 효율적으로 사용할 수 있겠다 싶어 사용하게 되었습니다.

그리고 검색 탭을 선택했지만 살펴보지 않는 경우나 
추후 검색 페이지의 추가로 영역이 늘어나 무거워지는 경우에 대비하고 싶어서 사용했는데

한정된 이미지만을 보여준다는 로라의 의견도 맞는것같아서 고민이 되네요!
이 건은 내일 스터디에서 한번 다 같이 이야기 해보면 좋은 이슈같습니다!
좋은 레퍼런스와 의견 진짜 감사하고 저도 너무 궁금하고 어려운 이슈라서 말씀해주신게 너무 좋네요!



 
lazy var로 선언 되어 있으면 좋겠ㄷ

2022-10-11 13:22 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    }
넵! 시로 말씀대로 `collectionView(minimumLineSpacingForSectionAt:_)`는 
셀과 셀 사이의 간격을 설정하는 부분이 맞고 저 역시 셀사이 간격을 주기위해 사용했습니다!👍

저는 `collectionView`의 `.scrollDirection = .horizontal`로 주었기 때문에 
위 아래 간격이 아닌 좌우에 간격을 10만큼 적용된거라고 생각해주시면 될 것 같아요!

2022-10-11 13:25 UTC, GODNOEL commented on IKEA/IKEA/SupportingView/RecentProductSectionView.swift
> +    }
음.. 저는 이미 `cellSize`라는 변수에 크기 값을 담았기 때문에 
추후 수정 시에  `cellSize` 변수만 바꾸면 될 것 같다라는 생각이 드는데 
(제가 아직 잘 몰라서..)

`CGSize`를 한번 더 변수로 선언했을 때 어떤 점이 더 편한지 아직은 잘 모르겠는데
혹시 예시를 말씀해 주실 수 있으신가요?🥹🥺

2022-10-11 13:27 UTC, GODNOEL commented
> 깔끔하고 좋은 코드 감사합니다. 보면서 정말 공부가 많이 되네요. PR에 코드를 리뷰하는건 처음이라서 좀 어색한데 몇가지 궁금한점이나 수정 제한사항(?)을 올릴게요.

시로! 
코드로 UI구현한 부분은 익숙하지 않으실텐데 리뷰 달아주셔서 감사합니다!!👍

2022-10-11 13:28 UTC, GODNOEL commented
> 고생하셨습니다!! 노엘 코드 보고 저도 코드 베이스로 UI 짜는 방법 공부하고 갑니다... 총총..🌝
> 
> 커밋할 때 이슈 넘버 잊지 말아주세요.. Remember me...

넵 로라 커밋할때마다 로라를 생각하겠습니다..!🥰

2022-10-12 12:46 UTC, taehyeonk approved these changes

2022-10-14 07:42 UTC, merged